<?php

$linkAbs = new a(PAGES_URL . "AbstractFactory.php","Abstract Factory");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Builder.php","Builder");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "FactoryMethod.php","Factory Method");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Prototype.php","Prototype");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Singleton.php","Singleton");
echo $linkAbs->getFull() . "<br><br>";
$linkAbs = new a(PAGES_URL . "Adapter.php","Adapter");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Bridge.php","Bridge");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Composite.php","Composite");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Decorator.php","Decorator");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Facade.php","Facade");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Flyweight.php","Flyweight");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Proxy.php","Proxy");
echo $linkAbs->getFull() . "<br><br>";
$linkAbs = new a(PAGES_URL . "Chain.php","Chain of Responsibility");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Command.php","Command");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Interpreter.php","Interpreter");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Iterator.php","Iterator");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Mediator.php","Mediator");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Memento.php","Memento");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Observer.php","Observer");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "State.php","State");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Strategy.php","Strategy");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "TemplateMethod.php","Template Method");
echo $linkAbs->getFull() . "<br>";
$linkAbs = new a(PAGES_URL . "Visitor.php","Visitor");
echo $linkAbs->getFull();